(function_definition "}" @end) @indent
(list ")" @end) @indent
(dict ")" @end) @indent
(call "]" @end) @indent
(index "]" @end) @indent
(conditional "]" @end) @indent
(conditional_dot "]" @end) @indent
(while_loop "]" @end) @indent
(for_loop "]" @end) @indent
